name    'lfisher47-stig_sysctl'
version '0.0.3'
author  'Leah Fisher'
license 'Apache2'
project_page 'https://github.com/lfisher47/puppet-stig_sysctl'
source  'git://github.com/lfisher47/puppet-stig_sysctl'
summary 'Sysctl STIG requirements'
description 'Sysctl STIG requirements'
dependency 'thias/sysctl'
dependency 'puppetlabs/stdlib'
